// <auto-generated />
namespace ArgosVetShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class New_Fields_on_AppointmentModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_Fields_on_AppointmentModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705290018205_New_Fields_on_AppointmentModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
