// <auto-generated />
namespace ArgosVetShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Date_Field_to_String_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Date_Field_to_String_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "201705290322356_Date_Field_to_String_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
